apiVersion: apps/v1
kind: Deployment
metadata:
   name: super-mario-app
   labels:
      app: super-mario-app
spec:
   replicas: 2
   selector:
      matchLabels:
         app: super-mario-app
   template:
      metadata:
         labels:
            app: super-mario-app
      spec:
          containers:
           -  name: super-mario-app 
              image: sevenajay/mario:latest
              imagePullPolicy: Always
              ports:
              - containerPort: 8080
              resources:
               limits:
                  memory: "512Mi"
                  cpu: "500m"
               requests:
                  memory: "256Mi"
                  cpu: "250m" 